name: "diff"
# Version is the version of Helm plus the number of official builds for this
# plugin
version: "2.11.0+3"
usage: "Preview helm upgrade changes as a diff"
description: "Preview helm upgrade changes as a diff"
useTunnel: true
command: "/usr/bin/helm-diff"
